<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="4" hostname="DESKTOP-2RLMOET" name="com.crm.comcast.organisationtest.Create_OrgTest" tests="5" failures="0" timestamp="8 Nov 2021 11:00:18 GMT" time="0.089" errors="1">
  <testcase name="create_org" time="0.069" classname="com.crm.comcast.organisationtest.Create_OrgTest">
    <skipped/>
  </testcase> <!-- create_org -->
  <testcase name="create_org" time="0.003" classname="com.crm.comcast.organisationtest.Create_OrgTest">
    <skipped/>
  </testcase> <!-- create_org -->
  <testcase name="create_org" time="0.006" classname="com.crm.comcast.organisationtest.Create_OrgTest">
    <skipped/>
  </testcase> <!-- create_org -->
  <testcase name="create_org" time="0.007" classname="com.crm.comcast.organisationtest.Create_OrgTest">
    <error type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.fail(Assert.java:53)
	at com.crm.comcast.organisationtest.Create_OrgTest.create_org(Create_OrgTest.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:958)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1160)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:607)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- create_org -->
  <testcase name="create_org" time="0.004" classname="com.crm.comcast.organisationtest.Create_OrgTest">
    <skipped/>
  </testcase> <!-- create_org -->
</testsuite> <!-- com.crm.comcast.organisationtest.Create_OrgTest -->
